name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ tenki-standard-medium-4c-8g , macos-latest, windows-latest ]
        go-version: [ '1.26', '1.27' ]
    steps:
      - name: Configure Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false # fixes go lint fmt error
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Lint
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
      - name: Test
        uses: n8maninger/action-golang-test@aa292dc81b16d34406a9551e629e0cdca00d9418 # v2.2.1
        with:
          args: "-race;-tags='testing';-timeout=300s"
      - name: Build
        run: go build -o bin/ ./cmd/faucetd
